sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 19980909
  alioss:
    endpoint: https://oss-cn-guangzhou.aliyuncs.com
    bucket-name: web-testhaolin
    region: cn-guangzhou
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx9ffbfce2f6e92f2e
    secret: 86cba6e9d75eb6e5007c85a7107ade9f
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php