sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 19980909
  alioss:
    endpoint: https://oss-cn-guangzhou.aliyuncs.com
    bucket-name: web-testhaolin
    region: cn-guangzhou
  redis:
    host: localhost
    port: 6379
    database: 0